# Generated by Django 3.1 on 2020-09-04 19:29

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('Position', models.CharField(max_length=100, unique=True, verbose_name='Field Position')),
                ('FR', models.TextField(verbose_name='French Text')),
                ('UK', models.TextField(verbose_name='English Text')),
            ],
            options={
                'ordering': ['Position'],
            },
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['Position'], name='I_Position'),
        ),
    ]
